// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo_KcWdp-M527IDewS6rpTs7exgjsp-js',
    appId: '1:669853098768:web:821523f5828e87fcdf7b95',
    messagingSenderId: '669853098768',
    projectId: 'painal-1203',
    authDomain: 'painal-1203.firebaseapp.com',
    storageBucket: 'painal-1203.firebasestorage.app',
    measurementId: 'G-J0ERWD3DH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbc-bgXF5OQbX4ADttxMFbneyze36wM1I',
    appId: '1:669853098768:android:3829ace5325d72dddf7b95',
    messagingSenderId: '669853098768',
    projectId: 'painal-1203',
    storageBucket: 'painal-1203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9OudhhMNNLjSTwyvAVO1pCyC6X-m9pQ',
    appId: '1:669853098768:ios:8dca2db1dde65b9edf7b95',
    messagingSenderId: '669853098768',
    projectId: 'painal-1203',
    storageBucket: 'painal-1203.firebasestorage.app',
    iosBundleId: 'com.mohitxcodes.painal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9OudhhMNNLjSTwyvAVO1pCyC6X-m9pQ',
    appId: '1:669853098768:ios:8dca2db1dde65b9edf7b95',
    messagingSenderId: '669853098768',
    projectId: 'painal-1203',
    storageBucket: 'painal-1203.firebasestorage.app',
    iosBundleId: 'com.mohitxcodes.painal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo_KcWdp-M527IDewS6rpTs7exgjsp-js',
    appId: '1:669853098768:web:eca9498bdbcb6adcdf7b95',
    messagingSenderId: '669853098768',
    projectId: 'painal-1203',
    authDomain: 'painal-1203.firebaseapp.com',
    storageBucket: 'painal-1203.firebasestorage.app',
    measurementId: 'G-4JREZHSMWH',
  );
}
