import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
// import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:painal/apis/AuthProviderUser.dart';
import 'package:painal/apis/CheckUpdate.dart';
import 'package:painal/firebase_options.dart';
import 'package:painal/models/FamilyMember.dart';
import 'package:painal/screens/HomeScreen.dart';
import 'package:provider/provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await dotenv.load(fileName: ".env");
  await Hive.initFlutter();
  // await MobileAds.instance.initialize();
  Hive.registerAdapter(FamilyMemberAdapter()); // generated by build_runner
  await Hive.openBox<FamilyMember>('familyBox');
  runApp(
    ChangeNotifierProvider(
      create: (_) => AuthProviderUser(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Painal Village - पै़नाल गाँव',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        primaryColor: Colors.green[700],
        appBarTheme: AppBarTheme(
          backgroundColor: Colors.green[700],
          foregroundColor: Colors.white,
        ),
      ),
      home: UpdateCheckerScreen(),
    );
  }
}

class UpdateCheckerScreen extends StatefulWidget {
  const UpdateCheckerScreen({super.key});

  @override
  State<UpdateCheckerScreen> createState() => _UpdateCheckerScreenState();
}

class _UpdateCheckerScreenState extends State<UpdateCheckerScreen> {
  bool _updateChecked = false;

  @override
  void initState() {
    super.initState();
    _initUpdateCheck();
  }

  Future<void> _initUpdateCheck() async {
    await UpdateService.checkForImmediateUpdate();
    setState(() => _updateChecked = true);
  }

  @override
  Widget build(BuildContext context) {
    if (!_updateChecked) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    return HomeScreen();
  }
}
